function Figura(X1, Y1,titl)
%CREATEFIGURE(X1, Y1)
%  X1:  stem x
%  Y1:  stem y

%  Auto-generated by MATLAB on 15-Apr-2019 21:17:37

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create stem
stem(X1,Y1,'LineWidth',2,'Color',[1 0 0]);

% Create title
title(titl);

% Set the remaining axes properties
set(axes1,'Color',[1 0.968627452850342 0.921568632125854],'FontName',...
    'Century Gothic','XAxisLocation','origin','XGrid','on','YAxisLocation',...
    'origin','YGrid','on');
